source 'http://rubygems.org'

gem 'rails', '3.0.10'
gem 'sqlite3'
gem 'devise', '~> 1.4.9'
gem 'jquery-rails'
gem 'will_paginate', '~> 3.0.2'
#gem 'week', '~> 0.0.2'
#gem 'mongo', '~> 1.4.0'
  #gem 'mongoid', '~> 2.2.4'
  #gem 'bson_ext', '~> 1.4.0'

group :development, :test do
  gem 'pry'
  gem 'pry-doc'
  #gem 'fuubar', '0.0.6'
  gem 'fuubar'
  gem 'fuubar-cucumber'
  gem 'grb', '~> 0.4.1'
  gem "mongrel", "~> 1.2.0.pre2"
  #gem 'rspec', '2.5.0'
    #gem 'rspec-rails', '2.5.0'
  gem 'rspec'
    gem 'rspec-rails'
  gem 'annotate', "~> 2.4.0"
  #gem 'autotest', '4.4.6'
    #gem 'autotest-fsevent', '0.2.5'
    #gem 'autotest-growl', '0.2.9'
    #gem 'autotest-rails-pure', '4.1.2'
  gem 'autotest'
    gem 'autotest-fsevent'
    gem 'autotest-growl'
    gem 'autotest-rails-pure'
  gem 'factory_girl_rails', '1.0.1'
  gem 'faker', '~> 1.0.1'
  gem 'ruby-debug', :platforms => [:ruby_18]
  gem 'ruby-debug19', :platforms => [:ruby_19], :require => 'ruby-debug'
  #gem 'cucumber', '~> 0.10.2'
  #gem 'cucumber-rails', '~> 0.4.1'
  #gem 'capybara', '~> 1.1.2'
  gem 'escape_utils'
  gem 'cucumber'
  gem 'cucumber-rails'
  gem 'capybara'
  gem 'database_cleaner'
end

