require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe TimecardsController do

  def mock_timecard(stubs={})
    @mock_timecard ||= mock_model(Timecard, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all timecards as @timecards" do
      Timecard.stub(:all) { [mock_timecard] }
      get :index
      assigns(:timecards).should eq([mock_timecard])
    end
  end

  describe "GET show" do
    it "assigns the requested timecard as @timecard" do
      Timecard.stub(:find).with("37") { mock_timecard }
      get :show, :id => "37"
      assigns(:timecard).should be(mock_timecard)
    end
  end

  describe "GET new" do
    it "assigns a new timecard as @timecard" do
      Timecard.stub(:new) { mock_timecard }
      get :new
      assigns(:timecard).should be(mock_timecard)
    end
  end

  describe "GET edit" do
    it "assigns the requested timecard as @timecard" do
      Timecard.stub(:find).with("37") { mock_timecard }
      get :edit, :id => "37"
      assigns(:timecard).should be(mock_timecard)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created timecard as @timecard" do
        Timecard.stub(:new).with({'these' => 'params'}) { mock_timecard(:save => true) }
        post :create, :timecard => {'these' => 'params'}
        assigns(:timecard).should be(mock_timecard)
      end

      it "redirects to the created timecard" do
        Timecard.stub(:new) { mock_timecard(:save => true) }
        post :create, :timecard => {}
        response.should redirect_to(timecard_url(mock_timecard))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved timecard as @timecard" do
        Timecard.stub(:new).with({'these' => 'params'}) { mock_timecard(:save => false) }
        post :create, :timecard => {'these' => 'params'}
        assigns(:timecard).should be(mock_timecard)
      end

      it "re-renders the 'new' template" do
        Timecard.stub(:new) { mock_timecard(:save => false) }
        post :create, :timecard => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested timecard" do
        Timecard.stub(:find).with("37") { mock_timecard }
        mock_timecard.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :timecard => {'these' => 'params'}
      end

      it "assigns the requested timecard as @timecard" do
        Timecard.stub(:find) { mock_timecard(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:timecard).should be(mock_timecard)
      end

      it "redirects to the timecard" do
        Timecard.stub(:find) { mock_timecard(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(timecard_url(mock_timecard))
      end
    end

    describe "with invalid params" do
      it "assigns the timecard as @timecard" do
        Timecard.stub(:find) { mock_timecard(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:timecard).should be(mock_timecard)
      end

      it "re-renders the 'edit' template" do
        Timecard.stub(:find) { mock_timecard(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested timecard" do
      Timecard.stub(:find).with("37") { mock_timecard }
      mock_timecard.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the timecards list" do
      Timecard.stub(:find) { mock_timecard }
      delete :destroy, :id => "1"
      response.should redirect_to(timecards_url)
    end
  end

end
